export {
  EDGE_TOLERANCE_PX,
  clientToDevice,
  fitContain,
  type Box,
  type DevicePoint,
} from "./coords.ts";
export {
  ContactBook,
  SWIPE_SLOP_PX,
  clampDuration,
  gestureFromContact,
  wheelToSwipe,
  type ContactStart,
  type DeviceGesture,
  type SwipeGesture,
  type TapGesture,
} from "./gestures.ts";
export { keyboardToDevice, type KeyAction, type KeyInput } from "./keys.ts";
export {
  FLAG_KEY_OR_CONFIG,
  WIRE_HEADER_BYTES,
  WIRE_VERSION,
  annexBStartCodeLength,
  avcCodecString,
  buildAvcDecoderConfig,
  isOpusConfigPayload,
  isOpusHead,
  isOpusTags,
  lengthPrefixNals,
  packWirePacket,
  parseOpusHead,
  parseWirePacket,
  prepareVideoAccessUnit,
  routeAudioPacket,
  splitAnnexB,
  type AnnexBNal,
  type AudioRouteAction,
  type OpusHeadInfo,
  type PreparedVideo,
  type RoutedAudio,
  type WireHeader,
} from "./protocol.ts";
export {
  SOFT_LAUNCH_MARKET,
  SOFT_LAUNCH_STREAM,
  StrlixSession,
  assertImplementedTransport,
  browserSocketFactory,
  streamEndpoints,
  type ControlMessage,
  type SocketFactory,
  type SocketHandlers,
  type StreamEndpoints,
  type StreamTransport,
  type StrlixSocket,
} from "./session.ts";
